### ISSUE TITLE
Support for Cloze cards without Fill-in Answers

### ISSUE THREAD

**Issue by Pvazevedo** [lakesare/memcode#196]
It would be excellent if memcode had a third type of card, which mixed the use of the other two.

The third could hide words, but without the need to fill them in manually.

I think it could even be a variation setting for the second card type as well.

This limitation of having to write the answer is excellent for learning languages, for example, but it makes the entire review scheme slower and more cumbersome in other use cases.
Besides, this would significantly speed up the review of cloze cards.

**Comment by lakesare** [comment]
Agreed, this is also useful for when you're on the phone & typing in words is cumbersome.
I'd say it shouldn't be a separate type of a flashcard, it should be a setting that's stored in the localStorage in this menu.

<img width="656" alt="image" src="https://github.com/lakesare/memcode/assets/7578559/a8405e06-54b1-4138-89ac-6843ad9051e0">

If this setting is on, we click SEE ANSWER

<img width="1274" alt="image" src="https://github.com/lakesare/memcode/assets/7578559/2eb36767-fc8d-47f5-b8a9-d034bf5f5e6a">

but instead of NEXT, we see WRONG and CORRECT buttons:

<img width="1273" alt="image" src="https://github.com/lakesare/memcode/assets/7578559/c821d81d-6c2b-461c-a214-7a3f4f8bc773">

___

### Price assignment (re: [memcode#requesting-a-feature](https://github.com/lakesare/memcode#requesting-a-feature))

**Implementing TTS for cloze deletion & question-answer flashcards**: **$30**

**Comment by lakesare** [comment]
@Pvazevedo, implemented this feature: https://twitter.com/memcodeapp/status/1773837323433566467.

<img width="400" src="https://github.com/lakesare/memcode/assets/7578559/7274f782-fd06-462c-b6b8-e85f5a1ab54f">

<img width="700" src="https://github.com/lakesare/memcode/assets/7578559/fd9639ca-1ee9-424e-a184-ba6e4ee17d0d">
