### ISSUE TITLE
New Feature: Enable QuillJS indent format option in toolbar for text and list indent

### ISSUE THREAD

**Issue by daniel-eder** [lakesare/memcode#89]
To structure data on flashcards it would be great to be able to use text indent and multiple list levels (list indent).
It looks like you are using QuillJS, which already supports this, but it isn ot enabled on the toolbar, and the hotkey TAB is consumed by the navigation between cards.

My suggestion would be to enable this in the toolbar, and if possible, find a way to use the tab hotkey for indent as well.

**Comment by lakesare** [comment]
Quill didn't support nested lists the last time I checked, but I see there is some work going on https://github.com/quilljs/quill/issues/979.
Certainly a nice feature to have, maybe on shift+tab in our case. Thanks for the PR, looking into it!

**Comment by lakesare** [comment]
@daniel-eder, made it so that if you `tab` within the list - it adds the sublist, and if you `tab` outside the list, - we switch to the next flashcard.
Very happy about it, thank you for drawing my attention to this :-)

![image](https://user-images.githubusercontent.com/7578559/88478771-60723c80-cf64-11ea-867e-c46f82e28e23.png)

**Comment by daniel-eder** [comment]
That's a fantastic solution, thanks a lot
