### ISSUE TITLE
Editing Cards on Mobile/Tablets/Small Browser Windows

### ISSUE THREAD

**Issue by daniel-eder** [lakesare/memcode#99]
The "new problem" div as well as the existing card quill editor seems to only be shown on the /courses/<id> page if the page is of a certain width, below that width the page is view-only.

Is this intentional? Is there any way to prevent this behaviour?

**Comment by lakesare** [comment]
It's intentional, basically because it's hard to create/edit flashcards on mobile for the users anyway.
I received 2 requests for enabling flashcard editing on mobiles though, and this being the 3rd - I'm for enabling mobile editing 👍
You can take this issue, or I'll get to it when I have some time.

**Comment by daniel-eder** [comment]
Good to hear! Free time is a bit limited this month and next, so I can't take it just yet, but I'll give you a heads up if I do start working on it.

**Comment by lakesare** [comment]
Made it possible to full-fledged edit the flashcards on mobile.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/7578559/174500229-cc22e40e-068d-48f5-8523-40c8f10fe12e.png">
